# Generated by Django 2.1 on 2019-06-02 08:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MmvbMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name company')),
                ('ogrn', models.URLField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=13), django.core.validators.MaxLengthValidator(limit_value=13)], verbose_name='OGRN number')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site company')),
                ('regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuers', to='MmvbMain.Regions', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Issuer',
                'verbose_name_plural': 'Issuers',
            },
        ),
    ]
