# Generated by Django 2.1 on 2019-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MmvbMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_name', models.CharField(db_index=True, max_length=128, verbose_name='Administrative name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('munitipal_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Municipal name')),
                ('okato_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='OKATO code')),
                ('oktmo_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='OKTMO code')),
                ('postcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='Postcode')),
                ('state_uuid', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Unique number in the state address register')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
    ]
