# Generated by Django 2.1 on 2019-10-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MmvbMain', '0002_issuers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuers',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuers', to='MmvbMain.Regions', verbose_name='Regions'),
        ),
    ]
