# Generated by Django 2.1 on 2019-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MmvbMain', '0003_auto_20191026_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Brokerage account name')),
            ],
            options={
                'verbose_name': 'Brokerage account',
                'verbose_name_plural': 'Brokerage accounts',
            },
        ),
    ]
