# Generated by Django 2.1 on 2019-10-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MmvbMain', '0004_brokerageaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritiesTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name of securities type')),
            ],
            options={
                'verbose_name': 'Type of Securities',
                'verbose_name_plural': 'Types of Securities',
            },
        ),
    ]
